### ISSUE TITLE
dust get-deps doesn't work

### ISSUE THREAD

**Issue by hswick** [justinj/sparkles#1]
Hi I realize that I could easily just add your simple source file to my project. But I thought I'd let you know that I had some trouble installing via dust get-deps.

I have this in :dependencies [[justinj/sparkles "0.1.0-alpha"]]

This was the terminal output:
Downloading justinj/sparkles
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Dust encountered an error: "Didn't find a valid tarball at https://github.com/justinj/sparkles/archive/0.1.0-alpha.tar.gz"

It makes the proper directories in deps but they are empty

**Comment by justinj** [comment]
Hi! Can you try `[[justinj/sparkles "v0.1.0-alpha"]]` instead? Not sure why I put the `v` there...

**Comment by hswick** [comment]
That did the trick! Thanks!
Might be good to have that in the docs

**Comment by justinj** [comment]
I made another release as `0.1.1-alpha` to match what seems to be more standard for Pixie/Clojure, so it matches `project.edn`. Thanks for bringing this up!
